export const WEB3_CONNECTION = 'WEB3_CONNECTION';
export const HTTP_SERVICE_BASE_URL_TOKEN = 'HTTP_SERVICE_BASE_URL_TOKEN';
export const WEB3_STORAGE_DI_TOKEN = 'WEB3_STORAGE_DI_TOKEN';
export const WEB3_CONTRACT_TOOLKIT_DI_TOKEN = 'WEB3_CONTRACT_TOOLKIT_DI_TOKEN';